extends:
  - stylelint-config-recommended-scss
  - stylelint-config-html/astro
rules:
  selector-pseudo-class-no-unknown: [true, { ignorePseudoClasses: [global] }]
  scss/at-rule-no-unknown: null
  no-empty-source: null
