version: 0.2

env:
  variables:
    NODE_ENV: production
  parameter-store:
    FA_PRO_TOKEN: FontAwesomeProToken
    # TINA_CLIENT_ID:
    # TINA_CONTENT_TOKEN:
    # TINA_SEARCH_TOKEN:
  exported-variables:
    - FA_PRO_TOKEN

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install --cache .npm
  build:
    on-failure: ABORT
    commands:
      - npm run build
  post_build:
    commands:
      - |
        aws s3 sync --delete dist s3://$SITE_BUCKET \
          --cache-control 'max-age=31536000' \
          --exclude="*" \
          --include="_astro/*" \
          --include="_responsive-images/*" \
          --include="fonts/*" \
          --size-only
      - |
        aws s3 sync --delete dist s3://$SITE_BUCKET \
          --cache-control 'no-cache' \
          --exclude="_astro/*" \
          --exclude="_responsive-images/*" \
          --exclude="fonts/*"

cache:
  paths:
    - 'node_modules/**/*'
    - '.npm/**/*'
    - '.cache/**/*'
    - 'dist/_responsive-images/*'
    - 'dist/media/**/*'
